version: '3.9'

services:
    nginx-service:
        image: nginx:latest
        ports:
            - "11001:80"
        restart: always
        volumes:
            - ./nginx-service/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx-service/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx-service/sites-enabled:/etc/nginx/sites-enabled:ro
            - ./nginx-service/ssl:/etc/nginx/ssl
            - ./nginx-service/var/www:/var/www
    